name: new_animated_button
description: A customizable Flutter button with jelly/tap/hover animations, shape system, and optional glassmorphism.
version: 0.0.1
homepage: https://github.com/yourname/jelly_button

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
